# this file is a Dockerfile for building a Docker image for the FIM project. 
# It uses Python 3.9 as the base image, sets the working directory to /app, 
# and copies the requirements.txt file to the container. It then installs the 
# required dependenciesusing pip. 
# Finally, it copies the entire project into the container and sets the command to run 
# the main.py script when the container starts.
